apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devsecops-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: devsecops.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devsecops-svc
            port:
              number: 80
